### ISSUE TITLE
dev HEAD: error on `make deploy` when using Python 3.6

### ISSUE THREAD

**Issue by rex4539** [gandrewstone/bitcoin#1395]
```
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/Resources
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/Resources
/opt/local/bin/ginstall -c -m 644 src/qt/res/icons/bitcoin.icns Bitcoin-Qt.app/Contents/Resources/bitcoin.icns
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents
/opt/local/bin/ginstall -c -m 644 share/qt/Info.plist Bitcoin-Qt.app/Contents/Info.plist
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/MacOS
STRIPPROG="/opt/local/bin/strip" /bin/sh /Users/rex/BitcoinUnlimited/build-aux/install-sh -c -s  src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/Resources/Base.lproj
echo '{	CFBundleDisplayName = "Bitcoin Unlimited Cash Edition"; CFBundleName = "Bitcoin Unlimited Cash Edition"; }' > Bitcoin-Qt.app/Contents/Resources/Base.lproj/InfoPlist.strings
./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2 -volname Bitcoin-Unlimited-Cash-Edition
  File "./contrib/macdeploy/macdeployqtplus", line 204
    print "Inspecting with otool: " + binaryPath
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Inspecting with otool: " + binaryPath)?
make: *** [Bitcoin-Unlimited-Cash-Edition.dmg] Error 1
```

**Comment by sickpig** [comment]
Will look into it, @rex4539 thanks for the report

**Comment by rex4539** [comment]
I did a short Investigation and found the cause.

It's due to Python version.

If I make Python 2.7 the default then it works but if I make Python 3.6 the default then it fails.

I tested with Bitcoin ABC as well and `make deploy` works with Python 3.6 there.

**Comment by sickpig** [comment]
thanks for digging it up and sharing! it makes my work a lot easier!

**Comment by sickpig** [comment]
@rex4539 #1403 should fix the issue.

**Comment by rex4539** [comment]
On latest `git pull` after the merge, it now fails with

```
$ make deploy
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
/opt/local/bin/python3 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2 -volname Bitcoin-Unlimited-Cash-Edition
+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
Traceback (most recent call last):
  File "./contrib/macdeploy/macdeployqtplus", line 625, in <module>
    deploymentInfo = deployFrameworksForAppBundle(applicationBundle, config.strip, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 367, in deployFrameworksForAppBundle
    frameworks = getFrameworks(applicationBundle.binaryPath, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 214, in getFrameworks
    otoolLines = o_stdout.split("\n")
TypeError: a bytes-like object is required, not 'str'
make: *** [Bitcoin-Unlimited-Cash-Edition.dmg] Error 1
```

**Comment by sickpig** [comment]
ouch will look at it.

**Comment by sickpig** [comment]
just tried to reproduce the problem on a my mac env and unfortunately I wasn't able to. the process seems to have terminated successfully.

**Comment by rex4539** [comment]
Just to be sure I didn't have my repo in some weird state, I just performed the following:

1. `rm -rf BitcoinUnlimited`
2. `git clone https://github.com/BitcoinUnlimited/BitcoinUnlimited.git`
3. `cd BitcoinUnlimited`
4. `git checkout dev`
5. `./autogen.sh`
6. `./configure --with-gui=qt5`
7. `make -j8`
8. `make deploy`

Got exactly the same error.

I'm using Python 3.6.7

**Comment by sickpig** [comment]
ok thanks. I think I got what went wrong when I tried to reproduce your problem I got both py2 and py3 installed....

**Comment by sickpig** [comment]
@rex4539 
would you mind trying to change line 214 of ./contrib/macdeploy/macdeployqtplus into: 

```py3
otoolLines = o_stdout.split(b'\n')   
```

and retry to issue `make deploy` ?

**Comment by rex4539** [comment]
Still getting the same after changing the line:

```
$ make deploy
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
/opt/local/bin/gmkdir -p Bitcoin-Qt.app/Contents/MacOS
STRIPPROG="/opt/local/bin/strip" /bin/sh /Users/rex/BitcoinUnlimited/build-aux/install-sh -c -s  src/qt/bitcoin-qt Bitcoin-Qt.app/Contents/MacOS/Bitcoin-Qt
/opt/local/bin/python3 ./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2 -volname Bitcoin-Unlimited-Cash-Edition
+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
Traceback (most recent call last):
  File "./contrib/macdeploy/macdeployqtplus", line 625, in <module>
    deploymentInfo = deployFrameworksForAppBundle(applicationBundle, config.strip, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 367, in deployFrameworksForAppBundle
    frameworks = getFrameworks(applicationBundle.binaryPath, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 221, in getFrameworks
    line = line.replace("@loader_path", os.path.dirname(binaryPath))
TypeError: a bytes-like object is required, not 'str'
make: *** [Bitcoin-Unlimited-Cash-Edition.dmg] Error 1
```

I also have multiple Python versions installed.

```
$ python2 --version
Python 2.7.15
$ python3 --version
Python 3.6.7
```

**Comment by sickpig** [comment]
Ok will fix.

**Comment by sickpig** [comment]
#1438 should fix the issue.

**Comment by rex4539** [comment]
Verified as fixed. Thanks!
